# Site settings
title: The PWO Heritage Project
email: info@warfare.org.au
description: >
  Documenting Australia's naval history
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

collections:
  people:
    output: true
    permalink: /people/:path/

# Build settings
markdown: kramdown
